apiVersion: v1
kind: Pod
metadata:
  name: echobot
  namespace: gitops-series
spec:
  containers:
    - name: message
      image: ghcr.io/sngular/gitops-echobot:v0.1.0
      env:
        - name: CHARACTER
          value: "sngular utiliza gitops en sus entornos"
      resources:
        requests:
          cpu: 10m
          memory: 30Mi
        limits:
          cpu: 10m
          memory: 30Mi