---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: echobot
  namespace: gitops-series
spec:
  interval: 1m0s
  url: https://github.com/sngular/gitops-echobot.git
  secretRef:
    name: ssh-credentials
  ref:
    semver: ">=0.1.0 <1.0.0"
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/deploy
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: echobot
  namespace: gitops-series
spec:
  interval: 10m0s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: echobot
  validation: client
